In [1]:
import gym
import universe
import tensorflow as tf
import numpy as np

In [5]:
env = gym.make("CartPole-v0")

[2017-04-06 10:05:21,967] Making new env: CartPole-v0


In [20]:
input_shape = list(env.observation_space.shape)
output_shape = env.action_space.n

In [2]:
gru_unit_size = 16
gru_cell = tf.contrib.rnn.GRUCell(gru_unit_size)

In [3]:
x = tf.placeholder(tf.float32, [1, None] + input_shape, "x")
initial_state = gru_cell.zero_state(1, dtype=tf.float32)
output, final_state = tf.nn.dynamic_rnn(gru_cell, x, initial_state=initial_state)

In [22]:
with tf.variable_scope("softmax"):
    w_softmax = tf.get_variable("w_softmax", shape=[gru_unit_size, output_shape], 
                                initializer=tf.contrib.layers.xavier_initializer())
    b_softmax = tf.get_variable("b_softmax", shape=[output_shape], 
                                initializer=tf.constant_initializer(0))

In [23]:
logit = tf.matmul(tf.reshape(output, [-1, gru_unit_size]), w_softmax) + b_softmax

In [27]:
prob = tf.nn.softmax(logit)

In [29]:
def action(prob):
    return np.random.choice(output_shape, p=prob)

In [4]:
session = tf.InteractiveSession()

In [46]:
env_state = env.reset()
states = [env_state]
actions = 
for _ in range(5):
    p = prob.eval({x: np.array([[env_state]])})
    a = action(p[0])
    env_state, reward, done, _ = env.step(a)
    states.append(env_state)
    

In [9]:
t = np.array([[env_state]])

In [25]:
session.run(tf.global_variables_initializer())

In [54]:
np.array([states])

array([[[ 0.03583439, -0.01552227, -0.02202406, -0.02863024],
        [ 0.03552394,  0.17990848, -0.02259667, -0.32817983],
        [ 0.03912211, -0.01488461, -0.02916027, -0.04270764],
        [ 0.03882442,  0.18064309, -0.03001442, -0.34444641],
        [ 0.04243728,  0.37617887, -0.03690335, -0.6464409 ],
        [ 0.04996086,  0.18159003, -0.04983216, -0.36560348]]])

In [57]:
final_state.eval({x: np.array([states])})

array([[ 0.13425873,  0.13091666,  0.01987722, -0.07110289,  0.05040483,
         0.0908491 ,  0.0052139 , -0.16597813, -0.03095519, -0.08463304,
        -0.01963032, -0.13310876,  0.01891536, -0.08630788,  0.02064023,
        -0.13375406]], dtype=float32)

In [56]:
final_state.eval({x: t})

array([[ -6.23138901e-03,   5.04083873e-04,  -3.41130095e-03,
         -4.78623016e-03,  -3.91389709e-03,   4.17959318e-03,
         -4.97021573e-03,  -2.22982885e-03,   7.49237090e-03,
          2.88198772e-03,   4.46935697e-03,   3.18044145e-03,
         -6.15646277e-05,   3.78778856e-03,  -4.10104170e-03,
          1.25843345e-03]], dtype=float32)